In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("final_destinations.csv")

In [3]:
df['type'].unique()

array(['heritage', 'religious', 'adventure', 'city', 'wildlife'],
      dtype=object)

In [4]:
df['budget_category'].unique()

array(['low', 'medium', 'luxury', 'high'], dtype=object)

In [5]:
def calculate_score(row, user):

    score = 0

    if row["type"] == user["type"]:
        score += 3

    if row["budget_category"] == user["budget"]:
        score += 2

    if row["best_season"] == user["season"]:
        score += 2

    if row["region"] == user["region"]:
        score += 2

    if user["activities"] in row["activities"]:
        score += 3
        
    score += row["rating"] * 0.2
    score += row["popularity_score"] * 0.02

    return score

In [6]:
user_input = {
    "type": "adventure",
    "budget": "high",
    "season": "summer",
    "activities": "trekking",
    "region": "North"
}

In [7]:
df['score'] = df.apply(lambda row : calculate_score(row, user_input), axis=1)

In [8]:
extra = df[["state","region"]].drop_duplicates()
extra.rename(columns={"state" : "destination"},inplace=True)
df = pd.concat([df,extra],ignore_index=True)
df

,state,destination,latitude,longitude,interest,region,type,activities,budget_category,best_season,rating,popularity_score,description,score
0,delhi,India Gate,28.612912,77.229510,cultural & heritage sites,North,heritage,"culture,forts,shopping,history",low,winter,4.6,53.0,India Gate is a heritage destination in delhi ...,3.98
1,delhi,Humayun's Tomb,28.593285,77.250749,cultural & heritage sites,North,heritage,"culture,forts,shopping,history",low,winter,4.5,80.0,Humayun's Tomb is a heritage destination in de...,4.50
2,delhi,Akshardham Temple,28.612673,77.277262,religious & spiritual pilgrimages,North,religious,"temple,spiritual,peace",medium,all,4.6,84.0,Akshardham Temple is a religious destination i...,4.60
3,delhi,Waste to Wonder Park,28.592694,77.256972,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",medium,summer,4.1,71.0,Waste to Wonder Park is a adventure destinatio...,12.24
4,delhi,Jantar Mantar,28.627055,77.216627,"arts, science & literature attractions",North,city,"exploration,local experience",low,All,4.2,83.0,Jantar Mantar is a city destination in delhi k...,4.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1046,NaN,bihar,NaN,NaN,NaN,East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1047,NaN,haryana,NaN,NaN,NaN,North,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048,NaN,puducherry,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049,NaN,andaman and nicobar islands,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050,NaN,daman and diu,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
top_places = df.sort_values(by="score",ascending=False).head(5)

In [10]:
print(df.iloc[876])

state                                                          sikkim
destination                                             Doling Gompa
latitude                                                    27.351641
longitude                                                   88.323931
interest                            religious & spiritual pilgrimages
region                                                     North-East
type                                                        religious
activities                                     temple,spiritual,peace
budget_category                                                   low
best_season                                                       all
rating                                                           34.0
popularity_score                                                 92.0
description         Doling Gompa  is a religious destination in si...
score                                                            8.64
Name: 876, dtype: object

In [11]:
top_places

,state,destination,latitude,longitude,interest,region,type,activities,budget_category,best_season,rating,popularity_score,description,score
384,himachal pradesh,Boat riding in Chamera lake,32.619974,76.007740,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",high,summer,4.4,86.0,Boat riding in Chamera lake is a adventure des...,14.60
399,himachal pradesh,Rafting in river Beas,31.759176,76.092387,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",high,summer,4.5,82.0,Rafting in river Beas is a adventure destinati...,14.54
604,jammu and kashmir,Skiing in Gulmarg,34.048370,74.380479,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",high,summer,4.5,74.0,Skiing in Gulmarg is a adventure destination i...,14.38
437,uttarakhand,Tungnath Chandrashila trekk,30.486269,79.221245,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",high,summer,4.2,55.0,Tungnath Chandrashila trekk is a adventure des...,13.94
397,himachal pradesh,Lama Dugh Hike,32.248903,77.175013,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",luxury,summer,4.7,99.0,Lama Dugh Hike is a adventure destination in h...,12.92

In [12]:
df.columns

Index(['state', 'destination', 'latitude', 'longitude', 'interest', 'region',
       'type', 'activities', 'budget_category', 'best_season', 'rating',
       'popularity_score', 'description', 'score'],
      dtype='object')

In [13]:
df.isnull().sum()

state               32
destination          0
latitude            32
longitude           32
interest            32
region               0
type                32
activities          32
budget_category     32
best_season         32
rating              32
popularity_score    32
description         32
score               32
dtype: int64

In [14]:
df = df.dropna(subset=[
    "state",
    "latitude",
    "longitude",
    "interest",
    "type",
    "activities",
    "budget_category",
    "best_season",
    "rating",
    "popularity_score",
    "description",
    "score"
])

In [15]:
top_places

,state,destination,latitude,longitude,interest,region,type,activities,budget_category,best_season,rating,popularity_score,description,score
384,himachal pradesh,Boat riding in Chamera lake,32.619974,76.007740,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",high,summer,4.4,86.0,Boat riding in Chamera lake is a adventure des...,14.60
399,himachal pradesh,Rafting in river Beas,31.759176,76.092387,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",high,summer,4.5,82.0,Rafting in river Beas is a adventure destinati...,14.54
604,jammu and kashmir,Skiing in Gulmarg,34.048370,74.380479,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",high,summer,4.5,74.0,Skiing in Gulmarg is a adventure destination i...,14.38
437,uttarakhand,Tungnath Chandrashila trekk,30.486269,79.221245,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",high,summer,4.2,55.0,Tungnath Chandrashila trekk is a adventure des...,13.94
397,himachal pradesh,Lama Dugh Hike,32.248903,77.175013,adventure & outdoor activities,North,adventure,"trekking,rafting,paragliding",luxury,summer,4.7,99.0,Lama Dugh Hike is a adventure destination in h...,12.92

In [16]:
def recommend_cities(data, user):

    # filter by region
    filtered = data[data["region"] == user["region"]]

    # filter by type
    filtered = filtered[filtered["type"] == user["type"]]

    # अगर empty हो गया
    if len(filtered) == 0:
        filtered = data[data["region"] == user["region"]]

    # top states निकालो
    top_states = (
        filtered.groupby("state")
        .size()
        .sort_values(ascending=False)
        .head(3)
        .index
        .tolist()
    )

    return top_states

In [17]:
selected_state = "himachal Pradesh"

In [18]:
def recommended_spots(df,user,selected_state):

    filtered = df[df['state'] == selected_state]

    filtered['score'] = filtered.apply(
        lambda row : calculate_score(row,user), axis=1
    )

    top_spots = filtered.sort_values(by="score",ascending=False).head()

    return top_spots[["destination", "score"]]

In [19]:


cities = recommend_cities(df,user_input)
print("Suggested Cities : ",cities)

selected  = cities[0]

spots = recommended_spots(df,user_input,selected)
print(spots)

Suggested Cities :  ['uttarakhand', 'himachal pradesh', 'haryana']
                             destination  score
437          Tungnath Chandrashila trekk  13.94
489  Dayara Bugyal  trekking and camping  12.82
420            Giant swing or zip lining  12.82
412                          Cheena peak  12.80
979               Trekking to Vasuki Tal  12.76

C:\Users\HP\AppData\Local\Temp\ipykernel_32724\2484722996.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['score'] = filtered.apply(

In [20]:
df.iloc[979]

state                                                     uttarakhand
destination                                    Trekking to Vasuki Tal
latitude                                                    30.907039
longitude                                                   79.171652
interest            adventure & outdoor activities, sightseeing & ...
region                                                          North
type                                                        adventure
activities                               trekking,rafting,paragliding
budget_category                                                   low
best_season                                                    summer
rating                                                            4.7
popularity_score                                                 91.0
description         Trekking to Vasuki Tal is a adventure destinat...
score                                                           12.76
Name: 979, dtype: object

In [23]:
df.to_csv("Final_destination.csv",index=False)

In [26]:
df['longitude'].isnull().sum()

np.int64(0)

In [30]:
data = pd.read_csv("final_with_city.csv")
data[['destination','city']].head(20)

                                       destination                  city
0                                       India Gate             New Delhi
1                                   Humayun's Tomb                 Delhi
2                                Akshardham Temple                 Delhi
3                             Waste to Wonder Park                 Delhi
4                                    Jantar Mantar             New Delhi
5                                    Chandni Chowk                 Delhi
6                                     Lotus Temple                 Delhi
7                                         Red Fort                 Delhi
8                                 Agrasen ki Baoli             New Delhi
9                                   Sunder Nursery                 Delhi
10                           Garden of Five Senses                 Delhi
11                                    Lodhi Garden             New Delhi
12                  National Gallery of Modern Art             New Delhi
13                       National Zoological Park                Bayawat
14                                     Qutub Minar                 Delhi
15                      Shopping at Sarojini Nagar             New Delhi
16                         National Science Centre             New Delhi
17                                    Marine Drive  Mumbai City District
18                                Gateway of India                Mumbai
19  Chhatrapati Shivaji Maharaj Vastu Sangrahalaya                Mumbai

In [39]:
data['city'].value_counts()

city
shimla    1019
Name: count, dtype: int64